---
title: "4a. Key Species Per KO"
author: "Avril Metcalfe-Roach"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(phyloseq)
library(data.table)
library(ggpubr)
library(tidyverse)

# Phyloseq object of MetaCyc pathways
ps = readRDS('../Reference Files/functional_phyloseq_ko_stratified.rds')
```

```{r Select pathways of interest}
# Load significant pwys
sig_uni = readxl::read_xlsx('../Results/Supplementary Data/Differential Abundance/KO_Stats2.xlsx',sheet='univar') %>% 
  filter(q_val<0.05) %>% group_by(Species) %>% add_count() %>% filter(n>1) %>% 
  select(Species,association_dir) %>% unique
sig_multi = readxl::read_xlsx('../Results/Supplementary Data/Differential Abundance/KO_Stats2.xlsx',sheet='multivar') %>%
  filter(Variable=='StatusPD', Species %in% sig_uni$Species) %>% 
  group_by(DA) %>% mutate(q_val = p.adjust(p_val,method='BH')) %>% ungroup %>% 
  filter(q_val<0.05) %>% group_by(Species) %>% add_count() %>% filter(n>1) %>% 
  select(Species,association_dir) %>% unique

# Normalized data to calculate proportions
df2 = ps %>% subset_taxa(feature %in% sig_multi$Species) %>% psmelt()

df3 = df2 %>% group_by(Sample,feature) %>% 
  summarize(sum = sum(Abundance)) %>% ungroup()

df3 = df2 %>% left_join(df3) %>% 
  filter(sum>100) %>% 
  mutate(Proportion = Abundance/sum, .after='Abundance') %>% 
  select(OTU:Proportion,sum,everything())
nrow(df2)
nrow(df3)

# Determine average proportion 
df4 = df3 %>% group_by(feature,taxon) %>% 
  summarize(`Proportion (Mean)` = mean(Proportion),
            `Proportion (SD)` = sd(Proportion),
            `Proportion (min)` = min(Proportion),
            `Proportion (max)` = max(Proportion)) %>% ungroup

# Filter to include proportions above x%
df5 = df4 %>% filter(`Proportion (Mean)`>0.33)
nrow(df4)
nrow(df5)

# Make a table
df6 = df5 %>% group_by(taxon) %>% count() %>% arrange(-n)
nrow(df6)
```

```{r Format tables}
avg_prop = df4 %>% 
  rename(Feature = feature, Taxon = taxon) %>% 
  mutate(Taxon = sapply(.$Taxon, function(x){
    if(x!='unclassified') x = x %>% str_split('[.]') %>% .[[1]] %>% .[2]
    return(x)
  })) 

count_table = df6 %>% 
  mutate(`KO (%)` = round(n/nrow(sig_multi),2)) %>% 
  rename(Taxon = taxon, `KO (/59)` = n) %>% 
  mutate(Taxon = sapply(Taxon, function(x){
    if(x!='unclassified') x = x %>% str_split('[.]') %>% .[[1]] %>% .[2]
    return(x)
  })) 
```

```{r Save raw statistics}
writexl::write_xlsx(list('Avg Proportion' = avg_prop,
                    'Min 33% of Fun Term' = count_table),
                    '../Results/Supplementary Data/Differential Abundance/Stratified KO.xlsx')
```

```{r Plot}
test = tibble()
for(i in seq(0.1,1,0.05)){
  test = rbind(test, df4 %>% filter(`Proportion (Mean)`>i) %>% 
    group_by(taxon) %>% count() %>% arrange(-n) %>% 
    mutate(cutoff=i))
}

test = test %>% filter(taxon!='unclassified') %>% 
  # Remove genus info
  mutate(taxon = sapply(taxon, function(x){
    if(x!='unclassified') x = x %>% str_split('[.]') %>% .[[1]] %>% .[2]
    return(x)
  })) %>% 
  # Shorten taxa names
  mutate(taxon = sapply(taxon,function(x){
      a = x %>% str_remove('s__') %>% str_split('_') %>% .[[1]]
      a[1] = paste(str_sub(a[1],end=1),'.')
      return(paste(a[1],a[2]))
  })) %>% 
  mutate(n = n/nrow(sig_multi)) 

order = test %>% 
  filter(cutoff==0.1) %>% # At the lowest cutoff...
  filter(n>=0.05) %>% # ...is it at lesat 5% relevant?
  arrange(-n) %>% pull(taxon) %>% unique

test %>% 
  filter(taxon %in% order) %>%
  mutate(Taxon = factor(taxon,levels = order)) %>% 
  ggplot(aes(cutoff,n,col=Taxon)) +
  geom_jitter(height=0, width=0,size=2) +
  geom_line(size=1) +
  ylim(0,0.8) + xlim(0.1,1) +
  theme_minimal(base_size=18) +
  ylab('Prop. KO Terms') + xlab('Min Prop. Counts')

ggsave('../Results/Supplementary Figures/Key_KO_Species.jpeg',height=4.5, width=6.5)
```


