---
title: "Functional Data - Diversity"
author: "Avril Metcalfe-Roach"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(phyloseq)
library(ggpubr)
library(data.table)
library(vegan)
library(tidyverse)
gc()

# This rds file contains all four functional datasets (KO, COG, EC, MetaCyc).
ps = readRDS('../Reference Files/functional_phyloseq_rarefied.rds')

# Extract metadata from metacyc phyloseq
s = psmelt(ps$pwy) %>% select(-OTU,-Abundance,-any_of(c('Kingdom','Phylum','Class','Order',
                                                    'Family','Genus','Species'))) %>% unique

# Symmetry
# For all nonzero MDS3 components with R and L elements, the values below denote the asymmetry of the person's symptoms.
symm = read.csv('C:/Users/armetcal/OneDrive - UBC/Grad School/Data/HUMAN COHORT/Reference Files/Curated MDS-UPDRS Part III/Symmetry of UPDRS3 Symptoms.csv')
s = s %>% left_join(symm %>% select(Sample,symmetric))
```

# DIVERSITY ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```{r Set up}
otulist = lapply(ps,function(x) x@otu_table %>% as.matrix %>% as.data.frame)
```

## ALPHA DIVERSITY ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Using Shannon for alpha diversity.

```{r Alpha Diversity}
# This function will be run on each of the functional datasets.

run_alpha = function(x){

  # x = otulist[[1]]
  
  # Use Vegan package to calculate diversity
  df_alpha <- diversity(t(x), index='shannon', MARGIN = 1, base = exp(1)) %>%
    as.data.frame()
  df_alpha$Sample = rownames(df_alpha)
  df_alpha = df_alpha %>% left_join(s %>% select(Sample,Status,depth,Sex,laxatives))
  names(df_alpha)[1] = 'shannon'
  
  # Statistics
  g = summary(glm(shannon~Status+Sex+laxatives+depth,data = df_alpha))$coefficients
  w = wilcox.test(shannon~Status, data = df_alpha) %>% broom::tidy()

  # Save results
  alphalist <<- alphalist %>% append(list(df_alpha))
  glmlist <<- glmlist %>% append(list(g))
  wilcoxlist <<- wilcoxlist %>% append(list(w))
}

# Prep some empty lists
alphalist = list()
glmlist = list()
wilcoxlist = list()

# Run alpha diversity analysis
lapply(otulist,run_alpha)

# Edit outputs
names(alphalist) = c('COG Enzymes','KEGG','EC','MetaCyc')
names(glmlist) = c('COG Enzymes','KEGG','EC','MetaCyc')
names(wilcoxlist) = c('COG Enzymes','KEGG','EC','MetaCyc')

# Format univariate results
wilcoxlist = wilcoxlist %>% lapply(function(x) x %>% as.data.frame() %>% mutate(Variable='Status'))
for(i in 1:4){wilcoxlist[[i]] = wilcoxlist[[i]] %>% mutate(Type = names(wilcoxlist)[i])}

# Format multivariate results
glmlist = glmlist %>% lapply(function(x) x %>% as.data.frame() %>% rownames_to_column('Variable'))
for(i in 1:4){glmlist[[i]] = glmlist[[i]] %>% mutate(Type = names(glmlist)[i])}

# Output of all GLM data
glmall = bind_rows(glmlist) %>% select(Type,everything()) %>% 
  group_by(Variable) %>% mutate(qval = p.adjust(`Pr(>|t|)`)) %>% ungroup() %>% arrange(qval)

# Output of all Wilcoxon data
wilall = bind_rows(wilcoxlist) %>%
  group_by(Variable) %>% mutate(qval = p.adjust(p.value),.after='p.value') %>% ungroup() %>% arrange(qval)
```

## BETA DIVERSITY ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Using Bray-Curtis for beta diversity.

```{r Beta Univariate}
run_beta = function(x){
  print('Starting...')
  # x = otulist$pwy
  
  # Calculate the distance matrix:
  beta_dist <- vegdist(t(x), index = 'bray')
  # Scaling results with NMDS
  mds <- metaMDS(beta_dist)
  # Extract PCoA axes and format
  mds_data <- as.data.frame(mds$points)
  mds_data$`Sample` <- rownames(mds_data)
  mds_data <- mds_data %>% left_join(s %>% select(Sample,Status,depth,Sex,laxatives)) %>% 
    mutate(beta_type = 'Bray-Curtis')
  
  # Plot results
  p = ggplot(mds_data, aes(x = MDS1, y = MDS2, color = Status)) +
      geom_point(size = 2) + 
      stat_ellipse(size = 1) +
      theme_classic(base_size = 20) + 
      xlab('PCoA 1') + ylab('PCoA 2') +
      ggtitle('Bray-Curtis Beta Diversity')
  
  # Univariate Statistics
  g1 = adonis2(beta_dist ~ Status, data = mds_data)
  md2 = mds_data %>% filter(!is.na(laxatives),!is.na(Sex),!is.na(depth))
  bd2 = t(x);bd2 = bd2[rownames(bd2) %in% md2$Sample,]
  g2 = adonis2(bd2 ~ Status+Sex+laxatives+depth, 
               data = md2, method = 'bray', by='margin')
  
  plotbeta <<- plotbeta %>% append(list(p))
  betalist <<- betalist %>% append(list(mds_data))
  glmbeta <<- glmbeta %>% append(list(g1))
  glmbeta.m <<- glmbeta.m %>% append(list(g2))
}

plotbeta = list()
betalist = list()
glmbeta = list()
glmbeta.m = list()

lapply(otulist,run_beta)

names(plotbeta) = c('COG Enzymes','KEGG','EC','MetaCyc')
names(betalist) = c('COG Enzymes','KEGG','EC','MetaCyc')
names(glmbeta) = c('COG Enzymes','KEGG','EC','MetaCyc')
names(glmbeta.m) = c('COG Enzymes','KEGG','EC','MetaCyc')

# Add descriptive y axes
for(i in names(plotbeta)){
  plotbeta[[i]]$labels$title = i
}

# Beta Statistics

glmbeta = glmbeta %>% lapply(function(x) x %>% as.data.frame() %>% rownames_to_column('Variable'))
glmbeta.m = glmbeta.m %>% lapply(function(x) x %>% as.data.frame() %>% rownames_to_column('Variable'))
for(i in 1:length(glmbeta)){
  glmbeta[[i]] = glmbeta[[i]] %>% mutate(Type = names(glmbeta)[i])
  glmbeta.m[[i]] = glmbeta.m[[i]] %>% mutate(Type = names(glmbeta.m)[i])
}

# Output of all GLM data
glmbetaall = bind_rows(glmbeta) %>% select(Type,everything()) %>% filter(!(Variable %in% c('Residual','Total'))) %>% 
  mutate(qval = p.adjust(`Pr(>F)`,method='fdr') %>% round(3)) %>% arrange(`Pr(>F)`)
glmbetaall.m = bind_rows(glmbeta.m) %>% select(Type,everything()) %>% filter(!(Variable %in% c('Residual','Total'))) %>% 
  group_by(Variable) %>% 
  mutate(qval = p.adjust(`Pr(>F)`,method='fdr') %>% round(3)) %>% ungroup() %>% arrange(`Pr(>F)`)
```

# SAVE STATS ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```{r}
L.stats = list('Shannon Diversity Univariate' = wilall,
                         'Shannon Diversity Multivariate' = glmall,
                         'Bray-Curtis Univariate' = glmbetaall, 
                         'Bray-Curtis Multivariate' = glmbetaall.m)
# Will save at end
```

# SAVE PLOTS ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```{r}
temp = plotbeta
temp$`COG Enzymes` = temp$`COG Enzymes` + 
  annotate(geom='text', x=-0.25, y=0.25, size = 5, 
           label=paste0('Univar: q=',round(glmbetaall$qval[glmbetaall$Type=='COG Enzymes'],2))) + 
  annotate(geom='text', x=-0.23, y=0.18, size = 5, 
           label=paste0('Multivar: q=',
                        round(glmbetaall.m$qval[glmbetaall.m$Type=='COG Enzymes' & glmbetaall.m$Variable=='Status'],2)))
temp$`MetaCyc` = temp$`MetaCyc` + 
  annotate(geom='text', x=-0.05, y=0.14, size = 5, 
           label=paste0('Univar: q=',round(glmbetaall$qval[glmbetaall$Type=='MetaCyc'],2))) + 
  annotate(geom='text', x=-0.03, y=0.1, size = 5, 
           label=paste0('Multivar: q=',
                        round(glmbetaall.m$qval[glmbetaall.m$Type=='MetaCyc' & glmbetaall.m$Variable=='Status'],2)))
temp$`EC` = temp$`EC` + 
  annotate(geom='text', x=-0.05, y=0.17, size = 5, 
           label=paste0('Univar: q=',round(glmbetaall$qval[glmbetaall$Type=='EC'],2))) + 
  annotate(geom='text', x=-0.03, y=0.13, size = 5, 
           label=paste0('Multivar: q=',
                        round(glmbetaall.m$qval[glmbetaall.m$Type=='EC' & glmbetaall.m$Variable=='Status'],2)))
temp$`KEGG` = temp$`KEGG` + 
  annotate(geom='text', x=-0.14, y=0.27, size = 5, 
           label=paste0('Univar: q=',round(glmbetaall$qval[glmbetaall$Type=='KEGG'],2))) + 
  annotate(geom='text', x=-0.12, y=0.18, size = 5, 
           label=paste0('Multivar: q=',
                        round(glmbetaall.m$qval[glmbetaall.m$Type=='KEGG' & glmbetaall.m$Variable=='Status'],2)))

betaplot = ggarrange(plotlist=temp, common.legend = T)
#Will save plot at end
```

#_
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#_

# Test Symmetry

```{r Alpha Diversity}
# This function will be run on each of the functional datasets.

s2 = s %>% mutate(Status = ifelse(Status=='Ctrl','Ctrl',
                                  ifelse(symmetric=='Symmetric','PD (Symmetric)','PD (Asymmetric)'))) %>% 
  filter(!is.na(Status))

run_alpha = function(x){

  # x = otulist[[1]]
  
  # Use Vegan package to calculate diversity
  df_alpha <- diversity(t(x), index='shannon', MARGIN = 1, base = exp(1)) %>%
    as.data.frame()
  df_alpha$Sample = rownames(df_alpha)
  df_alpha = df_alpha %>% left_join(s2 %>% select(Sample,Status,depth,Sex,laxatives,symmetric))
  names(df_alpha)[1] = 'shannon'
  
  # Statistics
  g = summary(glm(shannon~Status+Sex+laxatives+depth,data = df_alpha))$coefficients
  w1 = wilcox.test(shannon~Status, data = df_alpha %>% filter(Status!='PD (Symmetric)')) %>%
    broom::tidy() %>% mutate(Group = 'PD (Asymmetric)',.before='statistic')
  w2 = wilcox.test(shannon~Status, data = df_alpha %>% filter(Status!='PD (Asymmetric)')) %>%
    broom::tidy() %>% mutate(Group = 'PD (Symmetric)',.before='statistic')
  w = rbind(w1,w2)

  # Save results
  alphalist <<- alphalist %>% append(list(df_alpha))
  glmlist <<- glmlist %>% append(list(g))
  wilcoxlist <<- wilcoxlist %>% append(list(w))
}

# Prep some empty lists
alphalist = list()
glmlist = list()
wilcoxlist = list()

# Run alpha diversity analysis
lapply(otulist,run_alpha)

# Edit outputs
names(alphalist) = c('COG Enzymes','KEGG','EC','MetaCyc')
names(glmlist) = c('COG Enzymes','KEGG','EC','MetaCyc')
names(wilcoxlist) = c('COG Enzymes','KEGG','EC','MetaCyc')

# Format univariate results
wilcoxlist = wilcoxlist %>% lapply(function(x) x %>% as.data.frame() %>% mutate(Variable='Status'))
for(i in 1:4){wilcoxlist[[i]] = wilcoxlist[[i]] %>% mutate(Type = names(wilcoxlist)[i])}

# Format multivariate results
glmlist = glmlist %>% lapply(function(x) x %>% as.data.frame() %>% rownames_to_column('Variable'))
for(i in 1:4){glmlist[[i]] = glmlist[[i]] %>% mutate(Type = names(glmlist)[i])}

# Output of all GLM data
glmall = bind_rows(glmlist) %>% select(Type,everything()) %>% 
  group_by(Variable) %>% mutate(qval = p.adjust(`Pr(>|t|)`)) %>% ungroup() %>% arrange(qval)

# Output of all Wilcoxon data
wilall = bind_rows(wilcoxlist) %>%
  group_by(Variable) %>% mutate(qval = p.adjust(p.value),.after='p.value') %>% ungroup() %>% arrange(qval)
```


```{r Beta Univariate}
run_beta = function(x){
  print('Starting...')
  # x = otulist$pwy
  # Ensure that everyone has status data
  x = x[,which(colnames(x) %in% s2$Sample)]
  
  # Calculate the distance matrix:
  beta_dist <- vegdist(t(x), index = 'bray')
  # Scaling results with NMDS
  mds <- metaMDS(beta_dist)
  # Extract PCoA axes and format
  mds_data <- as.data.frame(mds$points)
  mds_data$`Sample` <- rownames(mds_data)
  mds_data <- mds_data %>% left_join(s2 %>% select(Sample,Status,depth,Sex,laxatives,symmetric)) %>% 
    mutate(beta_type = 'Bray-Curtis')
  
  # Plot results
  p = ggplot(mds_data, aes(x = MDS1, y = MDS2, color = Status)) +
      geom_point(size = 2) + 
      stat_ellipse(size = 1) +
      theme_classic(base_size = 20) + 
      xlab('PCoA 1') + ylab('PCoA 2') +
      ggtitle('Bray-Curtis Beta Diversity')
  
  # Univariate Statistics - Symmetric
  mdsfilt = mds_data %>% filter(Status !='PD (Asymmetric)')
  betafilt = beta_dist %>% as.matrix() %>% 
    .[which(colnames(.) %in% mdsfilt$Sample),which(colnames(.) %in% mdsfilt$Sample)] %>%
    as.dist()
  
  g1 = adonis2(betafilt ~ Status, data = mdsfilt) %>% as.data.frame() %>% 
    mutate(Group = 'PD (Symmetric)')
  md2 = mdsfilt %>% filter(!is.na(laxatives),!is.na(Sex),!is.na(depth))
  bd2 = t(x);bd2 = bd2[rownames(bd2) %in% md2$Sample,]
  g2 = adonis2(bd2 ~ Status+Sex+laxatives+depth, 
               data = md2, method = 'bray', by='margin') %>% as.data.frame() %>% 
    mutate(Group = 'PD (Symmetric)')
  
  # Univariate Statistics - Asymmetric
  mdsfilt = mds_data %>% filter(Status !='PD (Symmetric)')
  betafilt = beta_dist %>% as.matrix() %>% 
    .[which(colnames(.) %in% mdsfilt$Sample),which(colnames(.) %in% mdsfilt$Sample)] %>%
    as.dist()
  
  g11 = adonis2(betafilt ~ Status, data = mdsfilt) %>% as.data.frame() %>% 
    mutate(Group = 'PD (Asymmetric)')
  md2 = mdsfilt %>% filter(!is.na(laxatives),!is.na(Sex),!is.na(depth))
  bd2 = t(x);bd2 = bd2[rownames(bd2) %in% md2$Sample,]
  g22 = adonis2(bd2 ~ Status+Sex+laxatives+depth, 
               data = md2, method = 'bray', by='margin') %>% as.data.frame() %>% 
    mutate(Group = 'PD (Asymmetric)')
  
  plotbeta <<- plotbeta %>% append(list(p))
  betalist <<- betalist %>% append(list(mds_data))
  glmbeta <<- glmbeta %>% append(list(rbind(g1,g11)))
  glmbeta.m <<- glmbeta.m %>% append(list(rbind(g2,g22)))
}

plotbeta = list()
betalist = list()
glmbeta = list()
glmbeta.m = list()

lapply(otulist,run_beta)

names(plotbeta) = c('COG Enzymes','KEGG','EC','MetaCyc')
names(betalist) = c('COG Enzymes','KEGG','EC','MetaCyc')
names(glmbeta) = c('COG Enzymes','KEGG','EC','MetaCyc')
names(glmbeta.m) = c('COG Enzymes','KEGG','EC','MetaCyc')

# Add descriptive y axes
for(i in names(plotbeta)){
  plotbeta[[i]]$labels$title = i
}

# Beta Statistics

glmbeta = glmbeta %>% lapply(function(x) x %>% as.data.frame() %>% rownames_to_column('Variable'))
glmbeta.m = glmbeta.m %>% lapply(function(x) x %>% as.data.frame() %>% rownames_to_column('Variable'))
for(i in 1:length(glmbeta)){
  glmbeta[[i]] = glmbeta[[i]] %>% mutate(Type = names(glmbeta)[i])
  glmbeta.m[[i]] = glmbeta.m[[i]] %>% mutate(Type = names(glmbeta.m)[i])
}

# Output of all GLM data
glmbetaall = bind_rows(glmbeta) %>% select(Type,everything()) %>% filter(!(Variable %in% c('Residual','Total','Residual1','Total1'))) %>% 
  group_by(Group) %>% 
  mutate(qval = p.adjust(`Pr(>F)`,method='fdr') %>% round(3)) %>% 
  ungroup %>% arrange(`Pr(>F)`)
glmbetaall.m = bind_rows(glmbeta.m) %>% select(Type,everything()) %>% filter(!(Variable %in% c('Residual','Total','Residual1','Total1'))) %>% 
  group_by(Variable,Group) %>% 
  mutate(qval = p.adjust(`Pr(>F)`,method='fdr') %>% round(3)) %>% ungroup() %>% arrange(`Pr(>F)`)
```

# SAVE STATS ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```{r}
L.stats.symm =append(L.stats,list('Symmetry - Shannon Diversity Uni' = wilall,
                         'Symmetry - Shannon Diversity Multi' = glmall,
                         'Symmetry - Bray-Curtis Uni' = glmbetaall, 
                         'Symmetry - Bray-Curtis Multi' = glmbetaall.m))
writexl::write_xlsx(L.stats.symm,
                    '../Results/Supplementary Data/Diversity of Functional Data.xlsx')
```

# SAVE PLOTS ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```{r}
temp = plotbeta
temp$`COG Enzymes` = temp$`COG Enzymes` + 
  annotate(geom='text', x=-0.25, y=0.25, size = 5, 
           label=paste0('Symm: q=',
                        signif(glmbetaall.m$qval[glmbetaall.m$Type=='COG Enzymes' &
                                                glmbetaall.m$Group=='PD (Symmetric)' &
                                                glmbetaall.m$Variable=='Status'],2))) + 
  annotate(geom='text', x=-0.25, y=0.18, size = 5, 
           label=paste0('Asymm: q=',
                        signif(glmbetaall.m$qval[glmbetaall.m$Type=='COG Enzymes' &
                                                glmbetaall.m$Group=='PD (Asymmetric)' &
                                                glmbetaall.m$Variable=='Status1'],2)))
# MetaCyc
temp$`MetaCyc` = temp$`MetaCyc` + 
  annotate(geom='text', x=-0.05, y=0.16, size = 5, 
           label=paste0('Symm: q=',
                        signif(glmbetaall.m$qval[glmbetaall.m$Type=='MetaCyc' &
                                                glmbetaall.m$Group=='PD (Symmetric)' &
                                                glmbetaall.m$Variable=='Status'],2))) + 
  annotate(geom='text', x=-0.05, y=0.13, size = 5, 
           label=paste0('Asymm: q=',
                        signif(glmbetaall.m$qval[glmbetaall.m$Type=='MetaCyc' &
                                                glmbetaall.m$Group=='PD (Asymmetric)' &
                                                glmbetaall.m$Variable=='Status1'],2)))
# EC
temp$`EC` = temp$`EC` + 
  annotate(geom='text', x=-0.05, y=0.18, size = 5, 
           label=paste0('Symm: q=',
                        signif(glmbetaall.m$qval[glmbetaall.m$Type=='EC' &
                                                glmbetaall.m$Group=='PD (Symmetric)' &
                                                glmbetaall.m$Variable=='Status'],2))) + 
  annotate(geom='text', x=-0.05, y=0.15, size = 5, 
           label=paste0('Asymm: q=',
                        signif(glmbetaall.m$qval[glmbetaall.m$Type=='EC' &
                                                glmbetaall.m$Group=='PD (Asymmetric)' &
                                                glmbetaall.m$Variable=='Status1'],2)))
# KEGG
temp$`KEGG` = temp$`KEGG` + 
  annotate(geom='text', x=-0.2, y=0.25, size = 5, 
           label=paste0('Symm: q=',
                        signif(glmbetaall.m$qval[glmbetaall.m$Type=='KEGG' &
                                                glmbetaall.m$Group=='PD (Symmetric)' &
                                                glmbetaall.m$Variable=='Status'],2))) + 
  annotate(geom='text', x=-0.2, y=0.18, size = 5, 
           label=paste0('Asymm: q=',
                        signif(glmbetaall.m$qval[glmbetaall.m$Type=='KEGG' &
                                                glmbetaall.m$Group=='PD (Asymmetric)' &
                                                glmbetaall.m$Variable=='Status1'],2)))

betaplotsymm = ggarrange(plotlist=temp, common.legend = T)
```

```{r}
library(cowplot)
plot_grid(betaplot,betaplotsymm, ncol = 2)+
  theme(plot.margin = margin(1,0.1,0.1,2, "cm")) +
  draw_label(label="A",x=-0.015,y=1, fontface = "bold", size = 40) +
  draw_label(label="B",x=0.47,y=1, fontface = "bold", size = 40)

ggsave('../Results/Supp Figures/Figure S2 - Functional Beta Diversity.pdf',width = 16,height=8)
```

