---
title: "4a. Key Species Per MetaCyc"
author: "Avril Metcalfe-Roach"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(phyloseq)
library(data.table)
library(ggpubr)
library(tidyverse)

plot_results = function(data,multi,name){
  test = tibble()
  for(i in seq(0.1,1,0.05)){
    test = rbind(test, data %>% filter(`Proportion (Mean)`>i) %>% 
      group_by(taxon) %>% count() %>% arrange(-n) %>% 
      mutate(cutoff=i))
  }
  
  test = test %>% filter(taxon!='unclassified') %>% 
    # Remove genus info
    mutate(taxon = sapply(taxon, function(x){
      if(x!='unclassified') x = x %>% str_split('[.]') %>% .[[1]] %>% .[2]
      return(x)
    })) %>% 
    # Shorten taxa names
    mutate(taxon = sapply(taxon,function(x){
        a = x %>% str_remove('s__') %>% str_split('_') %>% .[[1]]
        a[1] = paste(str_sub(a[1],end=1),'.')
        return(paste(a[1],a[2]))
    })) %>% 
    mutate(n = n/nrow(multi)) 
  
  order = test %>% 
    filter(cutoff==0.1) %>% # At the lowest cutoff...
    filter(n>=0.05) %>% # ...is it at lesat 5% relevant?
    arrange(-n) %>% pull(taxon) %>% unique
  
  p =  test %>% 
    filter(taxon %in% order) %>%
    mutate(Taxon = factor(taxon,levels = order)) %>% 
    ggplot(aes(cutoff,n,col=Taxon)) +
    geom_jitter(height=0, width=0,size=2) +
    geom_line(size=1) +
    ylim(0,0.8) + xlim(0.1,1) +
    theme_minimal(base_size=18) +
    ylab(paste0('Prop. ',name,' Terms')) + xlab('Min Prop. Counts')
  return(p) 
}
```

```{r MetaCyc}
# Phyloseq object of MetaCyc pathways
ps = readRDS('../Reference Files/functional_phyloseq_metacyc_stratified.rds')

# Load significant pwys
sig_uni = readxl::read_xlsx('../Results/Supplementary Data/Differential Abundance/MetaCyc_Stats.xlsx',sheet='univar') %>% 
  filter(q_val<0.05) %>% group_by(Species) %>% add_count() %>% filter(n>1) %>% 
  select(Species,association_dir) %>% unique
sig_multi = readxl::read_xlsx('../Results/Supplementary Data/Differential Abundance/MetaCyc_Stats.xlsx',sheet='multivar') %>%
  filter(Variable=='StatusPD', Species %in% sig_uni$Species) %>% 
  group_by(DA) %>% mutate(q_val = p.adjust(p_val,method='BH')) %>% ungroup %>% 
  filter(q_val<0.05) %>% group_by(Species) %>% add_count() %>% filter(n>1) %>% 
  select(Species,association_dir) %>% unique

# Normalized data to calculate proportions
df2 = ps %>% subset_taxa(feature %in% sig_multi$Species) %>% psmelt()

df3 = df2 %>% group_by(Sample,feature) %>% 
  summarize(sum = sum(Abundance)) %>% ungroup()

df3 = df2 %>% left_join(df3) %>% 
  filter(sum>100) %>% 
  mutate(Proportion = Abundance/sum, .after='Abundance') %>% 
  select(OTU:Proportion,sum,everything())
nrow(df2)
nrow(df3)

# Determine average proportion 
df.meta = df3 %>% group_by(feature,taxon) %>% 
  summarize(`Proportion (Mean)` = mean(Proportion),
            `Proportion (SD)` = sd(Proportion),
            `Proportion (min)` = min(Proportion),
            `Proportion (max)` = max(Proportion)) %>% ungroup

p.meta = plot_results(df.meta,sig_multi,'MetaCyc')
```

```{r KO}
ps = readRDS('../Reference Files/functional_phyloseq_ko_stratified.rds')

# Load significant pwys
sig_uni = readxl::read_xlsx('../Results/Supplementary Data/Differential Abundance/KO_Stats2.xlsx',sheet='univar') %>% 
  filter(q_val<0.05) %>% group_by(Species) %>% add_count() %>% filter(n>1) %>% 
  select(Species,association_dir) %>% unique
sig_multi = readxl::read_xlsx('../Results/Supplementary Data/Differential Abundance/KO_Stats2.xlsx',sheet='multivar') %>%
  filter(Variable=='StatusPD', Species %in% sig_uni$Species) %>% 
  group_by(DA) %>% mutate(q_val = p.adjust(p_val,method='BH')) %>% ungroup %>% 
  filter(q_val<0.05) %>% group_by(Species) %>% add_count() %>% filter(n>1) %>% 
  select(Species,association_dir) %>% unique

# Normalized data to calculate proportions
df2 = ps %>% subset_taxa(feature %in% sig_multi$Species) %>% psmelt()

df3 = df2 %>% group_by(Sample,feature) %>% 
  summarize(sum = sum(Abundance)) %>% ungroup()

df3 = df2 %>% left_join(df3) %>% 
  filter(sum>100) %>% 
  mutate(Proportion = Abundance/sum, .after='Abundance') %>% 
  select(OTU:Proportion,sum,everything())
nrow(df2)
nrow(df3)

# Determine average proportion 
df.ko = df3 %>% group_by(feature,taxon) %>% 
  summarize(`Proportion (Mean)` = mean(Proportion),
            `Proportion (SD)` = sd(Proportion),
            `Proportion (min)` = min(Proportion),
            `Proportion (max)` = max(Proportion)) %>% ungroup

p.ko = plot_results(df.ko,sig_multi, 'KO')
```

```{r EC}
ps = readRDS('../Reference Files/functional_phyloseq_ec_stratified.rds')

# Load significant pwys
sig_uni = readxl::read_xlsx('../Results/Supplementary Data/Differential Abundance/EC_Stats2.xlsx',sheet='univar') %>% 
  filter(q_val<0.05) %>% group_by(Species) %>% add_count() %>% filter(n>1) %>% 
  select(Species,association_dir) %>% unique
sig_multi = readxl::read_xlsx('../Results/Supplementary Data/Differential Abundance/EC_Stats2.xlsx',sheet='multivar') %>%
  filter(Variable=='StatusPD', Species %in% sig_uni$Species) %>% 
  group_by(DA) %>% mutate(q_val = p.adjust(p_val,method='BH')) %>% ungroup %>% 
  filter(q_val<0.05) %>% group_by(Species) %>% add_count() %>% filter(n>1) %>% 
  select(Species,association_dir) %>% unique

# Normalized data to calculate proportions
df2 = ps %>% subset_taxa(feature %in% sig_multi$Species) %>% psmelt()

df3 = df2 %>% group_by(Sample,feature) %>% 
  summarize(sum = sum(Abundance)) %>% ungroup()

df3 = df2 %>% left_join(df3) %>% 
  filter(sum>100) %>% 
  mutate(Proportion = Abundance/sum, .after='Abundance') %>% 
  select(OTU:Proportion,sum,everything())

# Determine average proportion 
df.ec = df3 %>% group_by(feature,taxon) %>% 
  summarize(`Proportion (Mean)` = mean(Proportion),
            `Proportion (SD)` = sd(Proportion),
            `Proportion (min)` = min(Proportion),
            `Proportion (max)` = max(Proportion)) %>% ungroup

p.ec = plot_results(df.ec,sig_multi, 'EC')
```

```{r COG}
ps = readRDS('../Reference Files/functional_phyloseq_cog_stratified.rds')

# Load significant pwys
sig_uni = readxl::read_xlsx('../Results/Supplementary Data/Differential Abundance/COG Enzymes_Stats2.xlsx',sheet='univar') %>% 
  filter(q_val<0.05) %>% group_by(Species) %>% add_count() %>% filter(n>1) %>% 
  select(Species,association_dir) %>% unique
sig_multi = readxl::read_xlsx('../Results/Supplementary Data/Differential Abundance/COG Enzymes_Stats2.xlsx',sheet='multivar') %>%
  filter(Variable=='StatusPD', Species %in% sig_uni$Species) %>% 
  group_by(DA) %>% mutate(q_val = p.adjust(p_val,method='BH')) %>% ungroup %>% 
  filter(q_val<0.05) %>% group_by(Species) %>% add_count() %>% filter(n>1) %>% 
  select(Species,association_dir) %>% unique

# Normalized data to calculate proportions
df2 = ps %>% subset_taxa(feature %in% sig_multi$Species) %>% psmelt()

df3 = df2 %>% group_by(Sample,feature) %>% 
  summarize(sum = sum(Abundance)) %>% ungroup()

df3 = df2 %>% left_join(df3) %>% 
  filter(sum>100) %>% 
  mutate(Proportion = Abundance/sum, .after='Abundance') %>% 
  select(OTU:Proportion,sum,everything())

# Determine average proportion 
df.cog = df3 %>% group_by(feature,taxon) %>% 
  summarize(`Proportion (Mean)` = mean(Proportion),
            `Proportion (SD)` = sd(Proportion),
            `Proportion (min)` = min(Proportion),
            `Proportion (max)` = max(Proportion)) %>% ungroup

p.cog = plot_results(df.cog,sig_multi, 'COG')
```
```{r Combine Plots}
p = ggarrange(plotlist = list(p.cog,p.ec,p.meta,p.ko))

ggsave('../Results/Supp Figures/Figure S3 - Significance Cutoffs.pdf',height=8,width = 12)
```

